<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.de-gupta</groupId>
        <artifactId>de-gupta-parent</artifactId>
        <version>0.2.0</version>
    </parent>

    <artifactId>cleanCrud</artifactId>
    <version>0.9.1-SNAPSHOT</version>

    <name>cleaCrud</name>
    <description>A library for implementing clean architecture based crud operations</description>
    <url>https://github.com/de-gupta/cleanCrud.git</url>

    <dependencies>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>aletheia</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.de-gupta</groupId>
            <artifactId>athena</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-aop</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-autoconfigure</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <optional>true</optional>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <scm>
        <connection>scm:git:ssh://git@github.com/de-gupta/cleanCrud.git</connection>
        <developerConnection>scm:git:ssh://git@github.com/de-gupta/cleanCrud.git</developerConnection>
        <url>https://github.com/de-gupta/cleanCrud.git</url>
        <tag>HEAD</tag>
    </scm>
</project>