module de.gupta.clean.crud
{
	requires transitive de.gupta.aletheia;
	requires transitive de.gupta.athena;
	requires transitive spring.context;
	requires transitive spring.beans;
	requires transitive spring.core;
	requires transitive spring.web;
	requires transitive spring.webmvc;
	requires transitive spring.aop;
	requires transitive spring.tx;
	requires transitive spring.data.jpa;
	requires transitive spring.data.commons;
	requires transitive jakarta.persistence;
	requires transitive jakarta.validation;
	requires transitive org.hibernate.orm.core;
	requires transitive org.apache.tomcat.embed.core;
	requires transitive org.aspectj.weaver;
	requires transitive org.slf4j;
	requires spring.boot;
	requires spring.boot.autoconfigure;
	requires com.fasterxml.jackson.databind;
	requires static org.springdoc.openapi.common;
	requires static io.swagger.v3.oas.models;

	exports de.gupta.clean.crud.template.domain.mapping;
	exports de.gupta.clean.crud.template.domain.mapping.fetch;
	exports de.gupta.clean.crud.template.domain.mapping.save;
	exports de.gupta.clean.crud.template.domain.mapping.update;
	exports de.gupta.clean.crud.template.domain.model;
	exports de.gupta.clean.crud.template.domain.model.builder;
	exports de.gupta.clean.crud.template.domain.model.exceptions;
	exports de.gupta.clean.crud.template.domain.model.exceptions.operation;
	exports de.gupta.clean.crud.template.domain.model.exceptions.resource;
	exports de.gupta.clean.crud.template.domain.model.exceptions.security;
	exports de.gupta.clean.crud.template.domain.model.exceptions.validation;
	exports de.gupta.clean.crud.template.domain.model.identified;
	exports de.gupta.clean.crud.template.domain.model.validation;
	exports de.gupta.clean.crud.template.domain.relationship;
	exports de.gupta.clean.crud.template.generation.specification;
	exports de.gupta.clean.crud.template.domain.service.constraints;
	exports de.gupta.clean.crud.template.domain.service.crud.policy;
	exports de.gupta.clean.crud.template.domain.service.equality;
	exports de.gupta.clean.crud.template.domain.service.query;
	exports de.gupta.clean.crud.template.domain.service.security;
	exports de.gupta.clean.crud.template.infrastructure.persistence.adapter.persistence.domain.id.adapter;
	exports de.gupta.clean.crud.template.infrastructure.persistence.adapter.persistence.domain.id.model;
	exports de.gupta.clean.crud.template.infrastructure.persistence.adapter.persistence.domain.id.repository;
	exports de.gupta.clean.crud.template.infrastructure.persistence.adapter.persistence.domain.id.service;
	exports de.gupta.clean.crud.template.infrastructure.persistence.adapter.persistence.domain.model;
	exports de.gupta.clean.crud.template.infrastructure.persistence.history.adapter;
	exports de.gupta.clean.crud.template.infrastructure.persistence.history.model;
	exports de.gupta.clean.crud.template.infrastructure.persistence.history.repository;
	exports de.gupta.clean.crud.template.infrastructure.persistence.history.service;
	exports de.gupta.clean.crud.template.infrastructure.persistence.model;
	exports de.gupta.clean.crud.template.infrastructure.persistence.model.properties;
	exports de.gupta.clean.crud.template.infrastructure.persistence.transaction;
	exports de.gupta.clean.crud.template.infrastructure.web;
	exports de.gupta.clean.crud.template.useCases.crud.common;
	exports de.gupta.clean.crud.template.useCases.crud.common.adapter.id;
	exports de.gupta.clean.crud.template.useCases.crud.common.adapter.model;
	exports de.gupta.clean.crud.template.useCases.crud.common.infrastructure.persistence.repository;
	exports de.gupta.clean.crud.template.useCases.crud.common.security;
	exports de.gupta.clean.crud.template.useCases.crud.common.utility;
	exports de.gupta.clean.crud.template.domain.aggregate.definition;
	exports de.gupta.clean.crud.template.domain.aggregate.intent;
	exports de.gupta.clean.crud.template.useCases.crud.aggregate.service;
	exports de.gupta.clean.crud.template.useCases.crud.delete.api.application;
	exports de.gupta.clean.crud.template.useCases.crud.delete.api.web;
	exports de.gupta.clean.crud.template.useCases.crud.delete.application.service;
	exports de.gupta.clean.crud.template.useCases.crud.delete.facade;
	exports de.gupta.clean.crud.template.useCases.crud.delete.infrastructure.persistence.repository;
	exports de.gupta.clean.crud.template.useCases.crud.delete.infrastructure.persistence.service;
	exports de.gupta.clean.crud.template.useCases.crud.fetch.api.application;
	exports de.gupta.clean.crud.template.useCases.crud.fetch.api.web;
	exports de.gupta.clean.crud.template.useCases.crud.fetch.application.service;
	exports de.gupta.clean.crud.template.useCases.crud.fetch.facade;
	exports de.gupta.clean.crud.template.useCases.crud.fetch.infrastructure.persistence.repository;
	exports de.gupta.clean.crud.template.useCases.crud.fetch.infrastructure.persistence.service;
	exports de.gupta.clean.crud.template.useCases.crud.save.api.application;
	exports de.gupta.clean.crud.template.useCases.crud.save.api.web;
	exports de.gupta.clean.crud.template.useCases.crud.save.application.service;
	exports de.gupta.clean.crud.template.useCases.crud.save.facade;
	exports de.gupta.clean.crud.template.useCases.crud.save.infrastructure.persistence.repository;
	exports de.gupta.clean.crud.template.useCases.crud.save.infrastructure.persistence.service;
	exports de.gupta.clean.crud.template.useCases.crud.update.api.application;
	exports de.gupta.clean.crud.template.useCases.crud.update.api.web;
	exports de.gupta.clean.crud.template.useCases.crud.update.application.service;
	exports de.gupta.clean.crud.template.useCases.crud.update.facade;
	exports de.gupta.clean.crud.template.useCases.crud.update.infrastructure.persistence.repository;
	exports de.gupta.clean.crud.template.useCases.crud.update.infrastructure.persistence.service;
	exports de.gupta.clean.crud.template.useCases.query.property.api.application;
	exports de.gupta.clean.crud.template.useCases.query.property.api.web;
	exports de.gupta.clean.crud.template.useCases.query.property.application.service;
	exports de.gupta.clean.crud.template.useCases.query.property.facade;
	exports de.gupta.clean.crud.template.useCases.query.specification.collection.api.application;
	exports de.gupta.clean.crud.template.useCases.query.specification.collection.api.web;
	exports de.gupta.clean.crud.template.useCases.query.specification.collection.application.service;
	exports de.gupta.clean.crud.template.useCases.query.specification.collection.application.service.adapter;
	exports de.gupta.clean.crud.template.useCases.query.specification.collection.facade;
	exports de.gupta.clean.crud.template.useCases.query.specification.domain.model;
	exports de.gupta.clean.crud.template.useCases.query.specification.domain.service.filter;
	exports de.gupta.clean.crud.template.useCases.query.specification.unique.api.application;
	exports de.gupta.clean.crud.template.useCases.query.specification.unique.api.behaviour;
	exports de.gupta.clean.crud.template.useCases.query.specification.unique.api.web;
	exports de.gupta.clean.crud.template.useCases.query.specification.unique.facade;
	exports de.gupta.clean.crud.template.useCases.query.suppliedProperty.collection.api.application;
	exports de.gupta.clean.crud.template.useCases.query.suppliedProperty.collection.api.web;
	exports de.gupta.clean.crud.template.useCases.query.suppliedProperty.collection.facade;
	exports de.gupta.clean.crud.template.useCases.query.suppliedProperty.unique.api.web;
	exports de.gupta.clean.crud.template.useCases.query.suppliedProperty.unique.facade;
	exports de.gupta.clean.crud.template.useCases.operationOLD.domain.model;
	exports de.gupta.clean.crud.template.useCases.operationOLD.domain.model.id;
	exports de.gupta.clean.crud.template.useCases.operationOLD.domain.policy.invariant;
	exports de.gupta.clean.crud.template.useCases.operationOLD.quarantine.application.service;
	exports de.gupta.clean.crud.template.useCases.operationOLD.quarantine.domain;
	exports de.gupta.clean.crud.template.useCases.operationOLD.quarantine.domain.model;
	exports de.gupta.clean.crud.template.useCases.operationOLD.quarantine.domain.policy;
	exports de.gupta.clean.crud.template.useCases.operationOLD.quarantine.domain.port;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.aggregate.service;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.api.application;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.application.service;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.handler;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.model;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.plan;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.policy.access;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.policy.consistency;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.policy.evaluation;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.policy.invariant;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.policy.profile;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.policy.quarantine;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.domain.policy.transition;
	exports de.gupta.clean.crud.template.useCases.operationOLD.domain.policy.violation;
	exports de.gupta.clean.crud.template.useCases.operationOLD.quarantine.api.application;
	exports de.gupta.clean.crud.template.useCases.operationOLD.quarantine.api.web;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.quarantine.application;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.quarantine.application.recording;
	exports de.gupta.clean.crud.template.useCases.operationOLD.mutation.quarantine.infrastructure.spring;
	exports de.gupta.clean.crud.template.useCases.process.application.dispatch;
	exports de.gupta.clean.crud.template.useCases.process.application.execution;
	exports de.gupta.clean.crud.template.useCases.process.application.registration;
	exports de.gupta.clean.crud.template.useCases.process.domain.action;
	exports de.gupta.clean.crud.template.useCases.process.domain.definition;
	exports de.gupta.clean.crud.template.useCases.process.domain.model.id;
	exports de.gupta.clean.crud.template.useCases.process.domain.model.outcome;
	exports de.gupta.clean.crud.template.useCases.process.domain.model.policy;
	exports de.gupta.clean.crud.template.useCases.process.domain.model.task;
	exports de.gupta.clean.crud.template.useCases.process.infrastructure.persistence;
	exports de.gupta.clean.crud.template.useCases.process.infrastructure.persistence.model;
	exports de.gupta.clean.crud.template.useCases.process.infrastructure.spring;
	exports de.gupta.clean.crud.template.useCases.process.port.persistence;
	exports de.gupta.clean.crud.template.useCases.process.port.scheduling;
	exports de.gupta.clean.crud.template.infrastructure.persistence.history.audit;

	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.policy.access;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.aggregate.service;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.api.application;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.application.service;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.handler;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.model;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.plan;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.policy.consistency;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.policy.creation;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.policy.invariant;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.policy.evaluation;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.policy.profile;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.domain.policy.quarantine;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.quarantine.application;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.quarantine.application.recording;
	exports de.gupta.clean.crud.template.useCases.operationOLD.creation.quarantine.infrastructure.spring;

	opens de.gupta.clean.crud.template.useCases.process.infrastructure.persistence.model;
	opens de.gupta.clean.crud.template.useCases.process.infrastructure.persistence;
	opens de.gupta.clean.crud.template.useCases.process.infrastructure.spring;
	opens de.gupta.clean.crud.template.useCases.operationOLD.creation.quarantine.application;
	opens de.gupta.clean.crud.template.useCases.operationOLD.domain.model to com.fasterxml.jackson.databind;
	opens de.gupta.clean.crud.template.useCases.operationOLD.quarantine.api.web;
	opens de.gupta.clean.crud.template.useCases.operationOLD.quarantine.infrastructure.persistence.model;
	opens de.gupta.clean.crud.template.useCases.operationOLD.quarantine.infrastructure.persistence;
	opens de.gupta.clean.crud.template.useCases.operationOLD.creation.quarantine.infrastructure.spring;
	opens de.gupta.clean.crud.template.useCases.operationOLD.mutation.quarantine.application;
	opens de.gupta.clean.crud.template.useCases.operationOLD.mutation.quarantine.infrastructure.spring;

	opens de.gupta.clean.crud.template.infrastructure.web.openapi;
	exports de.gupta.clean.crud.template.domain.aggregate.port;
	exports de.gupta.clean.crud.template.domain.aggregate.relationship;
	exports de.gupta.clean.crud.template.domain.aggregate.execution;
	exports de.gupta.clean.crud.template.domain.aggregate.builder;
	exports de.gupta.clean.crud.template.infrastructure.aggregate.adapter;
	exports de.gupta.clean.crud.template.domain.aggregate.relationship.standard;
	exports de.gupta.clean.crud.template.domain.aggregate.lifecycle;
}